### ISSUE TITLE
Regular: Missing glyphs Latin/Common

### ISSUE THREAD

**Issue by jenskutilek** [jenskutilek/sudo-font#1]
['threesuperior', 'ae', 'OE', 'oe', 'tildecomb', 'uni0306', 'uni0309', 'uni030B', 'uni0312', 'uni0326', 'ellipsis', 'perthousand', 'uni2075', 'uni2076', 'uni2079', 'afii61352', 'summation', 'uni2215', 'uni2216', 'infinity', 'logicaland', 'logicalor', 'approxequal', 'integraltp', 'integralbt', 'uni0306.case', 'uni0309.case', 'uni030B.case']

**Comment by jenskutilek** [comment]
- [ ] ae
- [ ] oe
- [ ] w.wide
- [ ] A.sups
- [ ] B.sups
- [ ] D.sups
- [ ] E.sups
- [ ] G.sups
- [ ] J.sups
- [ ] K.sups
- [ ] M.sups
- [ ] N.sups
- [ ] O.sups
- [ ] P.sups
- [ ] Q.sups
- [ ] R.sups
- [ ] U.sups
- [ ] W.sups
- [ ] X.sups
- [ ] Y.sups
- [ ] Z.sups
- [ ] threesuperior
- [ ] fivesuperior
- [ ] sixsuperior
- [ ] ninesuperior
- [x] ellipsis
- [ ] yen
- [ ] anticlockwiseClosedCircleArrow
- [ ] divisionslash
- [ ] integralbt
- [ ] integraltp
- [ ] approxequal
- [ ] infinity
- [ ] logicaland
- [ ] logicalor
- [ ] integral
- [ ] summation
- [ ] perthousand
- [ ] setminus
- [ ] integral.001
- [x] shadelight
- [x] shademedium
- [x] shadedark
- [ ] cloud
- [x] blackstar
- [ ] whitestar
- [x] ballotBoxWithCheck
- [x] ballotBoxWithX
- [ ] lowerRightPencil
- [ ] banknoteDollarSign
- [ ] numero
- [ ] blackCircleForRecord
- [ ] blackLeftDoubleTriangle
- [ ] blackLeftDoubleTriangleWithVerticalBar
- [ ] blackMediumRightTriangle
- [ ] blackRightDoubleTriangle
- [ ] blackRightDoubleTriangleWithVerticalBar
- [ ] blackSquareForStop
- [ ] camera
- [ ] cityscape
- [ ] clockwiseRightAndLeftSemicircleArrows
- [ ] cloudRain
- [ ] crescentMoon
- [ ] doubleVerticalBar
- [ ] earthGlobeAmericas
- [ ] floppyDisk
- [ ] houseBuilding
- [ ] key
- [ ] maximize
- [ ] minimize
- [ ] personalComputer
- [ ] printer
- [ ] speaker
- [ ] speakerWithThreeSoundWaves
- [ ] speechBalloon
- [ ] tearOffCalendar
- [ ] telephoneReceiver
- [ ] thumbsDownSign
- [ ] thumbsUpSign
- [ ] wastebasket
- [ ] wrench
- [x] hungarumlautcomb
- [x] brevecomb
- [x] tildecomb
- [x] hookabovecomb
- [ ] commaturnedabovecomb
- [x] commaaccentcomb
- [x] hungarumlautcomb.case
- [x] brevecomb.case
- [x] tildecomb.case
- [ ] hookabovecomb.case
- [ ] dialytikatonoscomb
- [x] u1F6D2
- [ ] uniEC19
- [ ] uniEC27
- [ ] uniEC2A
- [ ] uniEC2B
- [ ] uniEC2C
- [ ] uniEC2D
- [ ] uniEC2E
- [ ] uniEC2F
- [ ] uniEC30

**Comment by harg** [comment]
Thank you for your amazing work on this font! :)
Do you plan to implement this? Some glyphs on that list are widely used (œ in french, ¥, ...)

**Comment by jenskutilek** [comment]
Some progress is being made ...

- [x] ae
- [x] oe
- [x] w.ss20
- [ ] w.wide
- [ ] A.sups
- [ ] B.sups
- [ ] D.sups
- [x] E.sups
- [ ] G.sups
- [ ] J.sups
- [ ] K.sups
- [ ] M.sups
- [ ] N.sups
- [ ] O.sups
- [x] P.sups
- [ ] Q.sups
- [ ] R.sups
- [ ] U.sups
- [ ] W.sups
- [ ] X.sups
- [ ] Y.sups
- [ ] Z.sups
- [x] threesuperior
- [x] fivesuperior
- [x] sixsuperior
- [x] ninesuperior
- [x] yen
- [ ] anticlockwiseClosedCircleArrow
- [x] divisionslash
- [x] integralbt
- [x] integraltp
- [x] approxequal
- [x] infinity
- [x] logicaland
- [x] logicalor
- [x] integral
- [x] summation
- [x] perthousand
- [x] setminus
- [x] integral.001
- [x] cloud
- [x] whitestar
- [x] ballotBoxWithCheck
- [ ] ballotBoxWithX
- [x] whiteFrowningFace
- [x] whiteSmilingFace
- [x] lowerRightPencil
- [ ] numero
- [ ] blackCircleForRecord
- [ ] blackLeftDoubleTriangle
- [ ] blackLeftDoubleTriangleWithVerticalBar
- [ ] blackMediumRightTriangle
- [ ] blackRightDoubleTriangle
- [ ] blackRightDoubleTriangleWithVerticalBar
- [ ] blackSquareForStop
- [ ] doubleVerticalBar
- [ ] earthGlobeAmericas
- [x] crescentMoon
- [x] cloudRain
- [ ] cityscape
- [ ] houseBuilding
- [x] thumbsUpSign
- [x] thumbsDownSign
- [x] speechBalloon
- [ ] banknoteDollarSign
- [ ] personalComputer
- [ ] floppyDisk
- [x] tearOffCalendar
- [x] telephoneReceiver
- [ ] camera
- [ ] speaker
- [ ] speakerWithThreeSoundWaves
- [x] key
- [ ] wrench
- [ ] printer
- [ ] wastebasket
- [ ] minimize
- [ ] maximize
- [ ] clockwiseRightAndLeftSemicircleArrows
- [x] grinningFace
- [x] grinningFaceWithSmilingEyes
- [x] smilingFaceWithSmilingEyes
- [x] commaturnedabovecomb
- [x] dialytikatonoscomb
- [ ] uniEC19
- [x] uniEC27
- [x] uniEC2A
- [x] uniEC2B
- [x] uniEC2C
- [ ] uniEC2D
- [x] uniEC2E
- [x] uniEC2F
- [ ] uniEC30

**Comment by jenskutilek** [comment]
Some progress is being made ...

- [ ] A.sups
- [ ] B.sups
- [ ] D.sups
- [ ] G.sups
- [ ] J.sups
- [ ] K.sups
- [ ] M.sups
- [ ] N.sups
- [ ] O.sups
- [ ] Q.sups
- [ ] R.sups
- [ ] U.sups
- [ ] W.sups
- [ ] X.sups
- [ ] Y.sups
- [ ] Z.sups
- [ ] anticlockwiseClosedCircleArrow
- [ ] ballotBoxWithX
- [ ] numero
- [ ] blackCircleForRecord
- [ ] blackLeftDoubleTriangle
- [ ] blackLeftDoubleTriangleWithVerticalBar
- [ ] blackMediumRightTriangle
- [ ] blackRightDoubleTriangle
- [ ] blackRightDoubleTriangleWithVerticalBar
- [ ] blackSquareForStop
- [ ] doubleVerticalBar
- [ ] earthGlobeAmericas
- [ ] cityscape
- [ ] houseBuilding
- [ ] banknoteDollarSign
- [ ] personalComputer
- [ ] floppyDisk
- [ ] camera
- [ ] speaker
- [ ] speakerWithThreeSoundWaves
- [ ] wrench
- [ ] printer
- [ ] wastebasket
- [ ] minimize
- [ ] maximize
- [ ] clockwiseRightAndLeftSemicircleArrows
- [ ] uniEC19
- [ ] uniEC2D
- [ ] uniEC30

**Comment by jenskutilek** [comment]
A.sups
B.sups
D.sups
G.sups
J.sups
K.sups
M.sups
N.sups
Q.sups
R.sups
U.sups
W.sups
X.sups
Y.sups
Z.sups
ballotBoxWithX
numero
blackCircleForRecord
blackLeftDoubleTriangle
blackLeftDoubleTriangleWithVerticalBar
blackMediumRightTriangle
blackRightDoubleTriangle
blackRightDoubleTriangleWithVerticalBar
blackSquareForStop
doubleVerticalBar
earthGlobeAmericas
cityscape
houseBuilding
banknoteDollarSign
personalComputer
floppyDisk
camera
speaker
speakerWithThreeSoundWaves
wrench
printer
wastebasket
minimize
maximize

**Comment by jenskutilek** [comment]
A.sups
B.sups
D.sups
G.sups
J.sups
K.sups
M.sups
N.sups
Q.sups
R.sups
U.sups
W.sups
X.sups
Y.sups
Z.sups
numero
earthGlobeAmericas
cityscape
houseBuilding
banknoteDollarSign
personalComputer
floppyDisk
camera
wrench
printer
wastebasket
minimize
maximize

**Comment by jenskutilek** [comment]
J.sups
K.sups
M.sups
Q.sups
U.sups
W.sups
X.sups
Y.sups
numero
earthGlobeAmericas
cityscape
houseBuilding
banknoteDollarSign
personalComputer
floppyDisk
camera
wrench
printer
wastebasket
minimize
maximize

**Comment by jenskutilek** [comment]
J.sups
K.sups
M.sups
U.sups
W.sups
X.sups
Y.sups
numero
earthGlobeAmericas
cityscape
houseBuilding
banknoteDollarSign
personalComputer
floppyDisk
camera
wrench
printer
wastebasket
minimize
maximize

**Comment by jenskutilek** [comment]
J.sups
K.sups
M.sups
U.sups
W.sups
X.sups
Y.sups
earthGlobeAmericas
cityscape
houseBuilding
banknoteDollarSign
personalComputer
floppyDisk
camera
wrench
printer
wastebasket
minimize
maximize

**Comment by jenskutilek** [comment]
earthGlobeAmericas
cityscape
houseBuilding
banknoteDollarSign
personalComputer
floppyDisk
camera
wrench
printer
wastebasket
minimize
maximize
