### ISSUE TITLE
Windows can't identify sudo-bold.ttf as a bold font.

### ISSUE THREAD

**Issue by yn0793** [jenskutilek/sudo-font#10]
Maybe the subfamily is incorrect or there is no style-linking.

**Comment by yn0793** [comment]
![image](https://user-images.githubusercontent.com/32827924/55973838-e65b6d00-5cb8-11e9-8d7b-76c424daed83.png)

**Comment by jenskutilek** [comment]
Works for me in Windows 10 ... are you using the [latest release](https://github.com/jenskutilek/sudo-font/releases/tag/v0.37) of Sudo?

![Bildschirmfoto 2019-04-12 um 10 02 41](https://user-images.githubusercontent.com/3185950/56021660-49c1bb00-5d0a-11e9-852f-48c3cc21d73a.png)

**Comment by jenskutilek** [comment]
Hm, but there is something that looks off in the name table … will investigate (the Italic and Bold weights shouldn't need name ID 16 and 17)

![Bildschirmfoto 2019-04-12 um 10 05 45](https://user-images.githubusercontent.com/3185950/56021797-9dcc9f80-5d0a-11e9-9d4a-5265a3496343.png)

**Comment by jenskutilek** [comment]
Could you try the [new release 0.38](https://github.com/jenskutilek/sudo-font/releases/tag/v0.38), it should be fixed now.

**Comment by yn0793** [comment]
@jenskutilek Problem solved, thanks a lot.
