### ISSUE TITLE
Some characters look “low resolution”

### ISSUE THREAD

**Issue by gnuvince** [jenskutilek/sudo-font#13]
I'm not sure exactly how to phrase this, but have a look at this image and notice that three glyphs are much more pixelated than their “siblings”.

![image](https://user-images.githubusercontent.com/39868/65804411-c5e07b80-e14f-11e9-95ed-d0466808e377.png)

- **Font:** Sudo Variable
- **Version:** v0.40
- **Operating system:** Linux with Xorg
- **Xft settings:**
```
Xft.autohint: 0
Xft.antialias: 1
Xft.hinting: true
Xft.hintstyle: hintslight
Xft.rgba: rgb
Xft.lcdfilter: lcddefault
```

**Comment by kkga** [comment]
Yeah I've seen this with some Cyrillic glyphs too. I guess these are "placeholders" for glyphs to be added?

**Comment by jenskutilek** [comment]
Yes, it's a known issue and comes from the way I worked: I started with pixel versions of all characters, but haven't yet drawn proper outlines for all of them.

**Comment by jenskutilek** [comment]
FWIW, unfinished base glyphs are marked red in this glyph proof: https://www.kutilek.de/sudo-font/sudo-regular-proof.pdf

**Comment by gnuvince** [comment]
Thanks for the info!
