### ISSUE TITLE
Vertical alignment issues on certain glyphs under some terminals

### ISSUE THREAD

**Issue by franciscod** [jenskutilek/sudo-font#15]
(basically a crosspost from https://github.com/kovidgoyal/kitty/issues/2086, which I'll quote)

Something's wrong with the alignment on the [Kitty terminal emulator](https://github.com/kovidgoyal/kitty):

![2019-10-23_01-45-18](https://user-images.githubusercontent.com/726447/67358440-c7c31200-f536-11e9-8afd-27e2ea5654df.png)

```

 AÁA
 EÉE
 IÍI
 OÓO
 UÚU

```

I don't remember seeing this issue with other fonts. On the other hand, [termite](https://github.com/thestinger/termite) seems to render this just fine.

Is there additional information that I can provide? Any experiments that I could make?

**Comment by jenskutilek** [comment]
Sorry, can't reproduce the issue here ... which OS are you running?

![Bildschirmfoto 2019-10-24 um 09 33 00](https://user-images.githubusercontent.com/3185950/67463231-5328ca00-f641-11e9-884f-3d4f8b55bc12.png)

**Comment by franciscod** [comment]
This happened on Arch Linux.

**Comment by franciscod** [comment]
More info on this comment by @ctrlcctrlv: https://github.com/kovidgoyal/kitty/issues/2086#issuecomment-571446443

Apparently there's something wrong with the grid fitting and seems solvable?

**Comment by jenskutilek** [comment]
The TrueType instructions for Sudo are done in [Glyphs.app](https://glyphsapp.com) but the accented letters actually don’t have any instructions of their own, only the ones inherited from the components. Weird …

**Comment by jenskutilek** [comment]
@franciscod I have tracked the issue down to the vertical metrics of the fonts. I have found a fix, but it changes the default line height of the font, so I’m not sure I like it ;)

Anyway, check out the [new release 0.41](https://github.com/jenskutilek/sudo-font/releases/tag/v0.41).

**Comment by franciscod** [comment]
Thanks! I hope you find the way to tweak it to your liking soon :)
