### ISSUE TITLE
Wrong glyph for U+1D7B LATIN SMALL CAPITAL LETTER I WITH STROKE

### ISSUE THREAD

**Issue by dscorbett** [jenskutilek/sudo-font#18]
The glyph for U+1D7B LATIN SMALL CAPITAL LETTER I WITH STROKE instead looks like a dotless ⟨i⟩ with stroke.

**Comment by jenskutilek** [comment]
Nice catch! The glyph name in Glyphs.app is misleading (idotlessstroke), that is probably why the wrong glyph ended up there.

**Comment by schriftgestalt** [comment]
How is the name misleading? 
"looks like a dotless ⟨i⟩ with stroke" vs "idotlessstroke"

**Comment by schriftgestalt** [comment]
The macOS system font seems to have it wrong, too. `uni026A` has serifs but `uni1D7B`doesn’t.
<img width="189" alt="Screenshot" src="https://user-images.githubusercontent.com/174660/94409843-fef26800-0176-11eb-9cbc-8aae66e0064b.png">

**Comment by jenskutilek** [comment]
The Unicode chart shows that it should be indeed a small cap i, not a dotless i. For sans-serif fonts the difference may not be noticeable ...

![Bildschirmfoto 2020-09-28 um 10 41 21](https://user-images.githubusercontent.com/3185950/94410031-3234f700-0177-11eb-9972-722e816eb963.png)

**Comment by jenskutilek** [comment]
It's also wrong in Consolas ;)

**Comment by schriftgestalt** [comment]
And there is similar case `uni1D7E; LATIN SMALL CAPITAL LETTER U WITH STROKE`.

**Comment by jenskutilek** [comment]
Fixed in [v0.51](https://github.com/jenskutilek/sudo-font/releases/tag/v0.51)
