### ISSUE TITLE
Wrong glyphs for X dingbats

### ISSUE THREAD

**Issue by dscorbett** [jenskutilek/sudo-font#19]
The glyphs for U+2716 HEAVY MULTIPLICATION X and U+2717 BALLOT X are essentially identical. U+2716 should be heavier. U+2717 should look more handwritten and asymmetrical. The current U+2716 glyph would be appropriate for U+2715 MULTIPLICATION X.

**Comment by jenskutilek** [comment]
Thank you for your suggestions. I've added more ballot boxes, Xs and check marks that have been added to Unicode, and made them all more consistent in [release 0.61](https://github.com/jenskutilek/sudo-font/releases/tag/v0.61).
