### ISSUE TITLE
Glyph for 1 different in variable font

### ISSUE THREAD

**Issue by svercl** [jenskutilek/sudo-font#21]
In the variable font the 1 is not the same as the regular fonts.

In variable:
![image](https://user-images.githubusercontent.com/3598852/117054588-dcfa2e80-acdf-11eb-95eb-23993910879f.png)

In regular:
![image](https://user-images.githubusercontent.com/3598852/117054649-f4391c00-acdf-11eb-8de4-02f531ea29e2.png)

**Comment by jenskutilek** [comment]
I can reproduce it. Interesting ...

**Comment by svercl** [comment]
This looks fixed in your latest release.

**Comment by jenskutilek** [comment]
Thanks. There were some more small bugs in the release, I've fixed them and replaced the variable font in sudo.zip [on the release page](https://github.com/jenskutilek/sudo-font/releases/tag/v0.53.0).
