### ISSUE TITLE
Variable font glyphs

### ISSUE THREAD

**Issue by svercl** [jenskutilek/sudo-font#22]
Hello again, the variable font is not correct. Some glyphs are missing the dot and others are incorrect, the 1 glyph issue has resurfaced as well. (#21)

![variable-dist sudo](https://user-images.githubusercontent.com/3598852/123151583-3998e080-d429-11eb-9688-ff0868d43361.png)

**Comment by jenskutilek** [comment]
I moved the source files to Glyphs 3 format, that introduced some regressions, and uncovered some new Glyphs bugs ;)

Fixed again in [v0.55.2](https://github.com/jenskutilek/sudo-font/releases/tag/v0.55.2), thanks for reporting!
