### ISSUE TITLE
Line-height is too large on Linux

### ISSUE THREAD

**Issue by kkga** [jenskutilek/sudo-font#23]
The current line-height feels a bit too large and the vertical centering of characters looks off.

Left is what I would consider correct line-height and character alignment (done with adjustments in the terminal), while right is how it looks by default. Both at 11pt.

![image](https://user-images.githubusercontent.com/1460122/133966395-ddb13d0e-6e15-459c-8df9-176ac78f97a2.png)

**Comment by jenskutilek** [comment]
True. I can squeeze the large accented letters some more, they are not commonly used in code. Fixed in 6b19f983e909245fbc8386f15e924a33534cb4e8 respectively [release 0.60](https://github.com/jenskutilek/sudo-font/releases/tag/v0.60).
