### ISSUE TITLE
ccmp feature not in release

### ISSUE THREAD

**Issue by moyogo** [jenskutilek/sudo-font#25]
The ccmp feature is in the source glyphspackage but isn’t in the release TTFs.

-  Some of the ligature stacking combining marks are not working but for this to work fully other things would be needed.
- The ccmp lookup for the softdotted substitution of i and j by idotless and jdotless should be in the TTFs, but dotless or decomposition of iogonek and istroke would also be needed.
- Case variants are not working but for this to work fully other things would be needed.

I think at least the softdotted lookup should be enabled as is for Dutch (or with dotless iogonek for Navajo and dotless istroke for others).

**Comment by jenskutilek** [comment]
Thank you! I disabled the ccmp/mark/mkmk features in the past for some reason. I think Glyphs didn't handle combining marks in monospaced fonts properly. But it seems to be fine in current Glyphs versions. Fixed in [release v0.72](https://github.com/jenskutilek/sudo-font/releases/tag/v0.72).

**Comment by moyogo** [comment]
Nice!
