### ISSUE TITLE
Missing letters and incorrect position of diacritics of DIN 91379 (Unicode subset for Europe)

### ISSUE THREAD

**Issue by vk-github18** [jenskutilek/sudo-font#26]
# Missing letters and incorrect position of diacritics of DIN 91379 (Unicode subset for Europe)

Please support all letters and sequences of DIN 91379 "Characters and defined character sequences in Unicode for the electronic processing of names and data exchange in Europe"

Some letters are missing and some diacritics are positioned incorrectly or not optimally.

Rendering using 
  hb-view (HarfBuzz) 2.8.1 
  Ubuntu 22.04.2 LTS
  Font from this GitHub repo

### Letters:
<code>  Ĳ ĳ Ḩ ḩ Ấ C̨̆ K̛ S̛̄ T̛ c̨̆ k̛ s̛̄ t̕ t̛ ʰ ʳ ˢ ᵈ ᵗ</code>

### Sudo
![letters_Sudo-Regular](https://github.com/jenskutilek/sudo-font/assets/39316085/e9f606e7-e5ef-4f64-98a2-14813ef368e0)
[letters_Sudo-Regular.pdf](https://github.com/jenskutilek/sudo-font/files/12329425/letters_Sudo-Regular.pdf)
[list_Sudo-Regular.pdf](https://github.com/jenskutilek/sudo-font/files/12329426/list_Sudo-Regular.pdf)

### Arimo
![letters_Arimo-Regular](https://github.com/jenskutilek/sudo-font/assets/39316085/8f871812-55aa-4176-b2ba-4e702118b8c4)
[letters_Arimo-Regular.pdf](https://github.com/jenskutilek/sudo-font/files/12329427/letters_Arimo-Regular.pdf)
[list_Arimo-Regular.pdf](https://github.com/jenskutilek/sudo-font/files/12329428/list_Arimo-Regular.pdf)

### Sudo
[latin_letters_all_Sudo-Regular.pdf](https://github.com/jenskutilek/sudo-font/files/12329447/latin_letters_all_Sudo-Regular.pdf)
[latin_list_all_Sudo-Regular.pdf](https://github.com/jenskutilek/sudo-font/files/12329449/latin_list_all_Sudo-Regular.pdf)

### Arimo
[latin_letters_all_Arimo-Regular.pdf](https://github.com/jenskutilek/sudo-font/files/12329431/latin_letters_all_Arimo-Regular.pdf)
[latin_list_all_Arimo-Regular.pdf](https://github.com/jenskutilek/sudo-font/files/12329433/latin_list_all_Arimo-Regular.pdf)

## See also
- https://github.com/String-Latin/DIN-91379-Characters-and-Sequences List of characters and sequences of DIN 91379
- https://en.wikipedia.org/wiki/DIN_91379

**Comment by jenskutilek** [comment]
Thank you. Could you specify what’s wrong about `Ấ` though? I think the rendering in Sudo is correct.

The sequences and missing characters are fixed in https://github.com/jenskutilek/sudo-font/releases/tag/v0.73 (but I made another unrelated update with https://github.com/jenskutilek/sudo-font/releases/tag/v0.74).

![din-91379-sequences](https://github.com/jenskutilek/sudo-font/assets/3185950/2850faf4-3f98-409f-9c3b-63126837f94c)
