### ISSUE TITLE
Regular: Missing glyphs Cyrillic

### ISSUE THREAD

**Issue by jenskutilek** [jenskutilek/sudo-font#3]
['afii10021', 'afii10024', 'afii10025', 'afii10038', 'afii10045', 'afii10048', 'afii10067', 'afii10069', 'afii10072', 'afii10073', 'afii10076', 'afii10077', 'afii10078', 'afii10086', 'afii10092', 'afii10093', 'afii10094', 'afii10095', 'afii10096', 'afii10097', 'afii10099', 'afii10106', 'afii10107']

**Comment by jenskutilek** [comment]
De-cy
Zhe-cy
Ze-cy
Ef-cy
Yeru-cy
Lje-cy
Nje-cy
Tshe-cy
Iu-cy
Dje-cy
ve-cy
de-cy
zhe-cy
ze-cy
ka-cy
el-cy
em-cy
ef-cy
softsign-cy
hardsign-cy
yeru-cy
lje-cy
nje-cy
iu-cy
ia-cy

**Comment by rellikmil** [comment]
@jenskutilek where are they? thanks you very much for font*

**Comment by jenskutilek** [comment]
- [x] De-cy
- [ ] Zhe-cy
- [ ] Ze-cy
- [ ] Ef-cy
- [ ] Yeru-cy
- [ ] Lje-cy
- [ ] Nje-cy
- [ ] Tshe-cy
- [ ] Iu-cy
- [ ] Dje-cy
- [ ] ve-cy
- [x] de-cy
- [ ] zhe-cy
- [ ] ze-cy
- [ ] ka-cy
- [ ] el-cy
- [ ] em-cy
- [ ] ef-cy
- [ ] softsign-cy
- [ ] hardsign-cy
- [ ] yeru-cy
- [ ] lje-cy
- [ ] nje-cy
- [ ] iu-cy
- [ ] ia-cy

**Comment by jenskutilek** [comment]
They are only there as pixel glyphs, no proper vectorized forms yet.

**Comment by jenskutilek** [comment]
Zhe-cy
Ze-cy
Ef-cy
Yeru-cy
Lje-cy
Nje-cy
Tshe-cy
Yu-cy
Dje-cy
zhe-cy
ze-cy
ka-cy
el-cy
em-cy
softsign-cy
yeru-cy
hardsign-cy
lje-cy
nje-cy
yu-cy
ya-cy

**Comment by jenskutilek** [comment]
Zhe-cy
Ze-cy
Ef-cy
Yeru-cy
Lje-cy
Nje-cy
Tshe-cy
Yu-cy
Dje-cy
zhe-cy
ze-cy
el-cy
em-cy
softsign-cy
yeru-cy
hardsign-cy
lje-cy
nje-cy
yu-cy
ya-cy
