### ISSUE TITLE
Slashed or dotted zero

### ISSUE THREAD

**Issue by akovski** [jenskutilek/sudo-font#7]
In sudo font, zero symbol is hard to distinguish from 'O' and 'o'.

**Comment by jenskutilek** [comment]
There is now a Python script included in the distribution, which you can use to swap the default zero with a dotted zero: [patch_dotted_zero.py](https://github.com/jenskutilek/sudo-font/blob/master/sudo/patch_dotted_zero.py) (You need the [Python Font Tools](https://github.com/behdad/fonttools) for this).
