### ISSUE TITLE
LICENSE fun

### ISSUE THREAD

**Issue by davelab6** [jenskutilek/sudo-font#8]
Please add an OFL.txt with a complete copy of the OFL and a copyright notice at the top, similar to eg https://github.com/davelab6/Varela-Round-Hebrew/tree/davelab6-smallfixes

Please also update the licensing information in the UFOs and the next release, eg
https://github.com/jenskutilek/sudo-font/blob/master/src/Sudo-Regular.ufo/fontinfo.plist#L35-L36

Including the whole license in the font is not required, the string I use is 

```
This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
```

I have notes on this and more in https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md :)

**Comment by jenskutilek** [comment]
Thanks for your input. Fixed in 53a5b7cfe76dae857e541404e83122ba12afd713.
