### ISSUE TITLE
Not work on emacs

### ISSUE THREAD

**Issue by jilen** [jenskutilek/sudo-font#9]
Font width is wrong on emacs actually.
![screenshot from 2019-03-08 12-41-48](https://user-images.githubusercontent.com/546573/54007987-906a4580-419f-11e9-9521-5d2a98d3cc58.png)

**Comment by jenskutilek** [comment]
Which version of Sudo are you using? Please try the [latest release](https://github.com/jenskutilek/sudo-font/releases/tag/v0.37) if you haven't already.

**Comment by jilen** [comment]
Thanks, seems I am using old version from aur
